MODEL:
  TYPE: swin_ang_den_unet
  NAME: woodscape_den_unet
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    FINAL_UPSAMPLE: "expand_first"
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: (1,16)
DATA:
  HIGH: 0.0
  LOW: 0.05